version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: ./
    image: joshhellstrom/flask_live_app:1.0.0
    command: flask run --host=0.0.0.0 --port=4000
    ports:
      - "4000:4000"
    environment:
      DB_URL: ${DATABASE_URI}  # Uses the ElephantSQL database
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URI}
    volumes:
      - ./:/app/soccer-proleagues-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      retries: 3
